import express from "express";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";
import dotenv from "dotenv";
import authRoutes from "./routes/auth.js";
import bookingRoutes from "./routes/bookings.js";
import masterRoutes from "./routes/masterData.js";
import reportRoutes from "./routes/reports.js";
import companyRoutes from "./routes/companyProfile.js";
import masterDataProRoutes from "./routes/masterDataPro.js";
import userRoutes from "./routes/users.js";
import roleRoutes from "./routes/roles.js";
import permissionRoutes from "./routes/permissions.js";
dotenv.config();
const app=express();
app.use(helmet({contentSecurityPolicy:false}));
app.use(cors({origin:process.env.FRONTEND_ORIGIN||"*",credentials:true}));
app.use(express.json({limit:"10mb"}));
app.use(morgan("dev"));
app.get("/api/health",(req,res)=>res.json({ok:true,service:"dive-booking-v4-api",time:new Date().toISOString()}));
app.use("/api/auth",authRoutes);
app.use("/api/bookings",bookingRoutes);
app.use("/api/master-data",masterRoutes);
app.use("/api/reports",reportRoutes);
app.use("/api/company-profile",companyRoutes);
app.use("/api/master-data-pro",masterDataProRoutes);
app.use("/api/users",userRoutes);
app.use("/api/roles",roleRoutes);
app.use("/api/permissions",permissionRoutes);
const port=process.env.PORT||3000;
app.listen(port,()=>console.log(`Dive Booking V4 API on ${port}`));
