import express from "express";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";
import dotenv from "dotenv";
import authRoutes from "./routes/auth.js";
import bookingRoutes from "./routes/bookings.js";
import masterRoutes from "./routes/masterData.js";
import reportRoutes from "./routes/reports.js";
import companyRoutes from "./routes/companyProfile.js";
import masterDataProRoutes from "./routes/masterDataPro.js";
import userRoutes from "./routes/users.js";
import roleRoutes from "./routes/roles.js";
import auditRoutes from "./routes/auditLogs.js";
import lineRoutes from "./routes/line.js";
import financialRoutes from "./routes/financial.js";
import permissionRoutes from "./routes/permissions.js";
dotenv.config();
const app=express();
app.use(helmet({contentSecurityPolicy:false}));
const allowedOrigins=(process.env.FRONTEND_ORIGIN||"").split(",").map(x=>x.trim()).filter(Boolean);
if(process.env.NODE_ENV==="production"&&!allowedOrigins.length)throw new Error("FRONTEND_ORIGIN is required in production");
app.use(cors({origin(origin,callback){if(!origin||!allowedOrigins.length||allowedOrigins.includes(origin))return callback(null,true);callback(new Error("Origin not allowed by CORS"));},credentials:true}));
app.use(express.json({limit:"10mb"}));
app.use(morgan("dev"));
app.get("/api/health",(req,res)=>res.json({ok:true,service:"sabina-tour-booking-api",time:new Date().toISOString()}));
app.use("/api/auth",authRoutes);
app.use("/api/bookings",bookingRoutes);
app.use("/api/master-data",masterRoutes);
app.use("/api/reports",reportRoutes);
app.use("/api/company-profile",companyRoutes);
app.use("/api/master-data-pro",masterDataProRoutes);
app.use("/api/users",userRoutes);
app.use("/api/roles",roleRoutes);
app.use("/api/permissions",permissionRoutes);
app.use("/api/audit-logs",auditRoutes);
app.use("/api/line",lineRoutes);
app.use("/api/financial",financialRoutes);
const port=process.env.PORT||3000;
export const server=app.listen(port,()=>console.log(`Sabina Tour Booking API on ${port}`));
export default app;
