import express from "express";import { requireAuth, requirePermission } from "../middleware/auth.js";import { supabaseAdmin } from "../services/supabase.js";
const router=express.Router();router.use(requireAuth);
router.get("/",async(req,res)=>{const {data,error}=await supabaseAdmin.rpc("list_bookings_json");if(error)return res.status(500).json({error:error.message});res.json(data||[])});
router.post("/",requirePermission("createBooking"),async(req,res)=>{const {data,error}=await supabaseAdmin.rpc("upsert_booking_from_json",{p_booking:req.body});if(error)return res.status(500).json({error:error.message});res.json(data)});
router.put("/:code",requirePermission("editBooking"),async(req,res)=>{const {data,error}=await supabaseAdmin.rpc("upsert_booking_from_json",{p_booking:{...req.body,bookingCode:req.params.code}});if(error)return res.status(500).json({error:error.message});res.json(data)});
router.post("/:code/cancel",requirePermission("cancelBooking"),async(req,res)=>{const {data,error}=await supabaseAdmin.rpc("cancel_booking_by_code",{p_booking_code:req.params.code,p_reason:req.body.reason});if(error)return res.status(500).json({error:error.message});res.json(data)});
router.post("/check-duplicate",async(req,res)=>{const b=req.body;const {data}=await supabaseAdmin.rpc("list_bookings_json");const d=(data||[]).filter(x=>x.travelDate===b.travelDate&&x.bookingCode!==b.bookingCode&&x.status!=="cancelled");const names=(b.passengers||[]).map(p=>`${p.title||""} ${p.firstName||""} ${p.lastName||""}`.trim().toLowerCase());const duplicates=[];d.forEach(x=>(x.passengers||[]).forEach(p=>{const n=`${p.title||""} ${p.firstName||""} ${p.lastName||""}`.trim().toLowerCase();if(names.includes(n))duplicates.push({bookingCode:x.bookingCode,name:n})}));res.json({duplicates})});
router.get("/:code/timeline",async(req,res)=>{const {data,error}=await supabaseAdmin.from("audit_logs").select("*").eq("booking_code",req.params.code).order("changed_at",{ascending:true});if(error)return res.status(500).json({error:error.message});res.json(data||[])});
export default router;
