import express from "express";
import { requireAuth, requirePermission } from "../middleware/auth.js";
import { supabaseAdmin } from "../services/supabase.js";
import { writeAudit } from "../services/auditService.js";

const router=express.Router();
router.use(requireAuth);
const M={programs:["master_programs","program_id","program_name","default_price"],accommodations:["master_accommodations","accommodation_id","accommodation_name"],addons:["master_addons","addon_id","addon_name","default_price"],agents:["master_agents","agent_id","agent_name"],boats:["master_boats","boat_id","boat_name"],islands:["master_islands","island_id","island_name"],customer_sources:["master_customer_sources","source_id","source_name"],transportation_methods:["master_transportation_methods","method_id","method_name","default_price"],price_reasons:["master_price_reasons","reason_id","reason_name"],payment_methods:["master_payment_methods","method_id","method_name"],statuses:["master_statuses","status_id","status_name"]};
function cfg(category){if(!M[category])throw Error("Invalid category");return M[category]}
function documentVisibility(category,body){const transport=category==="transportation_methods";return{show_register:body.show_register===true,show_money_receipt:transport?body.show_money_receipt===true:body.show_money_receipt!==false,show_equipment_slip:category==="addons"?body.show_equipment_slip!==false:body.show_equipment_slip===true,show_van_receipt:body.show_van_receipt===true,show_boat_ticket:body.show_boat_ticket===true,...(category==="addons"?{show_island_purchase_order:body.show_island_purchase_order===true}:{})}}
function payloadFor(category,body,{includeCode=false}={}){const [,id,name,price]=cfg(category),payload={[name]:body.name,active_flag:body.active_flag!==false,sort_order:body.sort_order||0,description:body.description||""};if(includeCode)payload[id]=body.code;if(price)payload[price]=body.default_price||0;if(category==="programs"){payload.child_price=body.child_price||0;payload.infant_price=body.infant_price||0}if(["addons","transportation_methods","accommodations"].includes(category))Object.assign(payload,documentVisibility(category,body));if(category==="payment_methods"){payload.payment_type=body.payment_type==="cash"?"cash":"transfer";payload.show_on_money_receipt=body.show_on_money_receipt!==false}return payload}

router.get("/:cat",async(req,res)=>{try{const [table]=cfg(req.params.cat),{data,error}=await supabaseAdmin.from(table).select("*").order("sort_order");if(error)throw error;res.json(data||[])}catch(error){res.status(500).json({error:error.message})}});
router.post("/:cat",requirePermission("editMasterData"),async(req,res)=>{try{const [table,id]=cfg(req.params.cat),payload=payloadFor(req.params.cat,req.body,{includeCode:true}),{data,error}=await supabaseAdmin.from(table).upsert(payload,{onConflict:id}).select().single();if(error)throw error;await writeAudit(req,{action:"MASTER_DATA_CREATED",detail:`เพิ่ม Master Data: ${req.params.cat}`,entityType:req.params.cat,entityId:String(data[id]),after:data});res.json(data)}catch(error){res.status(400).json({error:error.message})}});
router.put("/:cat/:id",requirePermission("editMasterData"),async(req,res)=>{try{const [table,id]=cfg(req.params.cat),{data:before}=await supabaseAdmin.from(table).select("*").eq(id,req.params.id).maybeSingle(),payload=payloadFor(req.params.cat,req.body),{data,error}=await supabaseAdmin.from(table).update(payload).eq(id,req.params.id).select().single();if(error)throw error;await writeAudit(req,{action:"MASTER_DATA_UPDATED",detail:`แก้ไข Master Data: ${req.params.cat}`,entityType:req.params.cat,entityId:req.params.id,before,after:data});res.json(data)}catch(error){res.status(400).json({error:error.message})}});

export default router;
