import express from "express";import { requireAuth, requirePermission } from "../middleware/auth.js";import { supabaseAdmin } from "../services/supabase.js";
const router=express.Router();router.use(requireAuth);
const M={programs:["master_programs","program_id","program_name","default_price"],addons:["master_addons","addon_id","addon_name","default_price"],agents:["master_agents","agent_id","agent_name"],boats:["master_boats","boat_id","boat_name"],islands:["master_islands","island_id","island_name"],price_reasons:["master_price_reasons","reason_id","reason_name"],payment_methods:["master_payment_methods","method_id","method_name"],statuses:["master_statuses","status_id","status_name"]};
function cfg(c){if(!M[c])throw Error("Invalid category");return M[c]}
router.get("/:cat",async(req,res)=>{const [t]=cfg(req.params.cat);const {data,error}=await supabaseAdmin.from(t).select("*").order("sort_order");if(error)return res.status(500).json({error:error.message});res.json(data||[])});
function programFields(category,body){if(category!=="programs")return{};const policy=String(body.accommodation_policy||"optional");if(!["none","required","optional"].includes(policy))throw new Error("Invalid accommodation policy");const credit=Number(body.self_booked_tent_credit||0);if(!Number.isFinite(credit)||credit<0)throw new Error("Invalid tent credit");return{accommodation_policy:policy,self_booked_tent_credit:credit}}
router.post("/:cat",requirePermission("editMasterData"),async(req,res)=>{try{const [t,id,n,price]=cfg(req.params.cat);const p={[id]:req.body.code,[n]:req.body.name,active_flag:req.body.active_flag!==false,sort_order:req.body.sort_order||0,description:req.body.description||"",...programFields(req.params.cat,req.body)};if(price)p[price]=req.body.default_price||0;const {data,error}=await supabaseAdmin.from(t).upsert(p,{onConflict:id}).select().single();if(error)throw error;res.json(data)}catch(error){res.status(400).json({error:error.message})}});
router.put("/:cat/:id",requirePermission("editMasterData"),async(req,res)=>{try{const [t,id,n,price]=cfg(req.params.cat);const p={[n]:req.body.name,active_flag:req.body.active_flag!==false,sort_order:req.body.sort_order||0,description:req.body.description||"",...programFields(req.params.cat,req.body)};if(price)p[price]=req.body.default_price||0;const {data,error}=await supabaseAdmin.from(t).update(p).eq(id,req.params.id).select().single();if(error)throw error;res.json(data)}catch(error){res.status(400).json({error:error.message})}});
export default router;
