import express from "express";
import { requireAuth, requirePermission } from "../middleware/auth.js";
import { supabaseAdmin } from "../services/supabase.js";
import { writeAudit } from "../services/auditService.js";

const router=express.Router();
router.use(requireAuth);
const M={programs:["master_programs","program_id","program_name","default_price"],accommodations:["master_accommodations","accommodation_id","accommodation_name","default_price"],addons:["master_addons","addon_id","addon_name","default_price"],island_addons:["master_island_addons","island_addon_id","island_addon_name","default_price"],package_cost_rates:["master_package_cost_rates","rate_id","cost_name","unit_rate"],island_boat_duties:["master_island_boat_duties","duty_id","duty_name"],agents:["master_agents","agent_id","agent_name"],boats:["master_boats","boat_id","boat_name"],islands:["master_islands","island_id","island_name"],booking_originals:["master_booking_originals","original_id","original_name"],customer_sources:["master_customer_sources","source_id","source_name"],transportation_methods:["master_transportation_methods","method_id","method_name","default_price"],price_reasons:["master_price_reasons","reason_id","reason_name"],payment_methods:["master_payment_methods","method_id","method_name"],statuses:["master_statuses","status_id","status_name"]};
function cfg(category){if(!M[category])throw Error("Invalid category");return M[category]}
function documentVisibility(category,body){const transport=category==="transportation_methods",island=category==="island_addons";return{show_register:body.show_register===true,show_money_receipt:transport?body.show_money_receipt===true:body.show_money_receipt!==false,show_equipment_slip:category==="addons"?body.show_equipment_slip!==false:body.show_equipment_slip===true,show_van_receipt:body.show_van_receipt===true,show_boat_ticket:body.show_boat_ticket===true,...(["addons","island_addons"].includes(category)?{show_island_purchase_order:body.show_island_purchase_order===true}:{}),...(island?{show_dive_receipt:body.show_dive_receipt!==false}:{})}}
function payloadFor(category,body,{includeCode=false}={}){const [,id,name,price]=cfg(category),payload={[name]:body.name,active_flag:body.active_flag!==false,sort_order:body.sort_order||0,description:body.description||""};if(includeCode)payload[id]=body.code;if(price)payload[price]=body.default_price||0;if(category==="programs"){payload.child_price=body.child_price||0;payload.infant_price=body.infant_price||0}if(category==="package_cost_rates"){payload.program_id=String(body.program_id||"").trim();payload.program_key=String(body.program_key||"").trim();payload.cost_code=String(body.cost_code||"").trim();payload.recipient_group=["park_food","park_fee","park_tent"].includes(payload.cost_code)?"park":"sabina";if(!payload.program_id||!payload.program_key||!payload.cost_code)throw Error("Program, report label and cost code are required")}if(["addons","island_addons","transportation_methods","accommodations"].includes(category))Object.assign(payload,documentVisibility(category,body));if(category==="payment_methods"){payload.payment_type=body.payment_type==="cash"?"cash":"transfer";payload.show_on_money_receipt=body.show_on_money_receipt!==false;payload.default_general=body.default_general===true;payload.default_equipment=body.default_equipment===true;payload.default_island=body.default_island===true;payload.default_transport=body.default_transport===true}return payload}

const paymentDefaultFields=["default_general","default_equipment","default_island","default_transport"];
async function clearCompetingPaymentDefaults(category,payload,currentId){if(category!=="payment_methods")return;for(const field of paymentDefaultFields){if(!payload[field])continue;let query=supabaseAdmin.from("master_payment_methods").update({[field]:false}).eq(field,true);if(currentId)query=query.neq("method_id",currentId);const {error}=await query;if(error)throw error}}

router.get("/:cat",async(req,res)=>{try{const [table]=cfg(req.params.cat),{data,error}=await supabaseAdmin.from(table).select("*").order("sort_order");if(error)throw error;res.json(data||[])}catch(error){res.status(500).json({error:error.message})}});
router.post("/:cat",requirePermission("editMasterData"),async(req,res)=>{try{const [table,id]=cfg(req.params.cat),payload=payloadFor(req.params.cat,req.body,{includeCode:true});await clearCompetingPaymentDefaults(req.params.cat,payload,payload[id]);const {data,error}=await supabaseAdmin.from(table).upsert(payload,{onConflict:id}).select().single();if(error)throw error;await writeAudit(req,{action:"MASTER_DATA_CREATED",detail:`เพิ่ม Master Data: ${req.params.cat}`,entityType:req.params.cat,entityId:String(data[id]),after:data});res.json(data)}catch(error){res.status(400).json({error:error.message})}});
router.put("/:cat/:id",requirePermission("editMasterData"),async(req,res)=>{try{const [table,id]=cfg(req.params.cat),{data:before}=await supabaseAdmin.from(table).select("*").eq(id,req.params.id).maybeSingle(),payload=payloadFor(req.params.cat,req.body);await clearCompetingPaymentDefaults(req.params.cat,payload,req.params.id);const {data,error}=await supabaseAdmin.from(table).update(payload).eq(id,req.params.id).select().single();if(error)throw error;await writeAudit(req,{action:"MASTER_DATA_UPDATED",detail:`แก้ไข Master Data: ${req.params.cat}`,entityType:req.params.cat,entityId:req.params.id,before,after:data});res.json(data)}catch(error){res.status(400).json({error:error.message})}});

export default router;
