import express from "express";
import { requireAuth, requirePermission } from "../middleware/auth.js";
import { supabaseAdmin } from "../services/supabase.js";
import { hashPassword } from "../services/passwordService.js";

const router=express.Router();router.use(requireAuth,requirePermission("manageUsers"));
const fields="user_id,username,email,display_name,role_id,active_flag,must_change_password,password_changed_at,last_login_at,failed_login_count,locked_until,created_at,updated_at";
const emailValue=value=>{const email=String(value||"").trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error("Valid email is required");return email};
async function audit(req,user,action,detail){try{const {error}=await supabaseAdmin.from("auth_audit_logs").insert({user_id:user?.user_id||null,username_snapshot:user?.username||null,email_snapshot:user?.email||null,action,success:true,detail,ip_address:req.ip,user_agent:String(req.headers["user-agent"]||"").slice(0,500)});if(error)throw error}catch(error){console.error("User audit failed",error.message)}}

router.get("/",async(req,res)=>{const {data,error}=await supabaseAdmin.from("app_users").select(fields).order("created_at");if(error)return res.status(500).json({error:error.message});res.json(data||[])});
router.post("/",async(req,res)=>{try{const passwordHash=await hashPassword(req.body.temporaryPassword);const payload={username:String(req.body.username||"").trim(),email:emailValue(req.body.email),display_name:String(req.body.display_name||"").trim(),role_id:req.body.role_id,active_flag:req.body.active_flag!==false,password_hash:passwordHash,must_change_password:true,password_changed_at:new Date().toISOString(),updated_at:new Date().toISOString()};if(!payload.username||!payload.display_name||!payload.role_id)throw new Error("Username, display name and role are required");const {data,error}=await supabaseAdmin.from("app_users").insert(payload).select(fields).single();if(error)throw error;await audit(req,data,"ADMIN_CREATE_USER",`Created by ${req.user.username}`);res.status(201).json(data)}catch(error){res.status(400).json({error:error.message})}});
router.put("/:id",async(req,res)=>{try{const {data:existing,error:existingError}=await supabaseAdmin.from("app_users").select("user_id,username,email,role_id,active_flag").eq("user_id",req.params.id).single();if(existingError)throw existingError;const disabling="active_flag" in req.body&&req.body.active_flag!==true,demoting="role_id" in req.body&&req.body.role_id!=="admin";if(existing.user_id===req.user.userId&&(disabling||demoting))throw new Error("Admin cannot deactivate or demote the current account");if(existing.role_id==="admin"&&existing.active_flag&&(disabling||demoting)){const {count,error:countError}=await supabaseAdmin.from("app_users").select("user_id",{count:"exact",head:true}).eq("role_id","admin").eq("active_flag",true);if(countError)throw countError;if(Number(count)<=1)throw new Error("At least one active admin account is required")}const payload={};if("email" in req.body)payload.email=emailValue(req.body.email);if("display_name" in req.body)payload.display_name=String(req.body.display_name||"").trim();if("role_id" in req.body)payload.role_id=req.body.role_id;if("active_flag" in req.body)payload.active_flag=req.body.active_flag===true;if(req.body.temporaryPassword){payload.password_hash=await hashPassword(req.body.temporaryPassword);payload.must_change_password=true;payload.password_changed_at=new Date().toISOString();payload.failed_login_count=0;payload.locked_until=null}payload.updated_at=new Date().toISOString();const {data,error}=await supabaseAdmin.from("app_users").update(payload).eq("user_id",req.params.id).select(fields).single();if(error)throw error;await audit(req,data,"ADMIN_UPDATE_USER",`Updated by ${req.user.username}`);res.json(data)}catch(error){res.status(400).json({error:error.message})}});
export default router;
