const buildBookingWithOriginal=buildBooking;
buildBooking=function(){const booking=buildBookingWithOriginal();booking.bookingOriginal=val("bookingOriginal");booking.boatTicketBookNo=val("boatTicketBookNo");booking.boatTicketNo=val("boatTicketNo");return booking};
const startNewBookingWithOriginal=startNewBooking;
startNewBooking=function(){startNewBookingWithOriginal();const original=document.getElementById("bookingOriginal");if(original)original.value=""};
const loadBookingWithOriginal=loadBookingToForm;
loadBookingToForm=function(booking){loadBookingWithOriginal(booking);setSelectValueWithHistory("bookingOriginal",booking.bookingOriginal)};
function bookingExportCounts(people){return people.reduce((counts,person)=>{const type=person.passengerType||"adult";counts[type]=(counts[type]||0)+1;return counts},{adult:0,child:0,infant:0,foc:0})}
function bookingExportDeposit(booking,type){return paymentMethodMeta(booking.depositPaymentMethod).payment_type===type?Number(booking.depositAmount||0):0}
bookingExcelRow=function(booking){const people=booking.passengers||[],counts=bookingExportCounts(people),programs=[...new Set(people.map(person=>person.program?.name).filter(Boolean))].join(", "),outbound=[...new Set(people.map(person=>person.transportationMethod).filter(Boolean))].join(", ")||booking.transportationMethod||"",outboundPlaces=[...new Set(people.map(person=>person.outboundDestination||person.transportationDestination).filter(Boolean))].join(", "),returns=[...new Set(people.map(person=>person.returnTransportationMethod).filter(Boolean))].join(", "),returnPlaces=[...new Set(people.map(person=>person.returnDestination).filter(Boolean))].join(", "),lodging=[...new Set(people.map(person=>person.accommodationName).filter(Boolean))].join(", ");return[booking.bookingOriginal||"",booking.source||"",excelDate(booking.createdAt),booking.receiptBookNo||"",booking.manualReceiptNo||"",booking.boatTicketBookNo||"",booking.boatTicketNo||"",[booking.leaderTitle,booking.leaderFirstName,booking.leaderLastName].filter(Boolean).join(" "),booking.phone||"",counts.adult,counts.child,counts.infant,counts.foc,programs,Number(booking.totalAmount||0),bookingExportDeposit(booking,"cash"),bookingExportDeposit(booking,"transfer"),excelDate(booking.travelDate),excelDate(booking.returnDate),outbound,outboundPlaces,returns,returnPlaces,lodging,booking.contactEmail||"",booking.bookingNote||""]};
exportBookingExcel=async function(){const from=val("pcDate"),to=val("pcToDate")||from;if(!from)return alert("เลือกวันที่เริ่มต้น");if(to<from)return alert("วันที่สิ้นสุดต้องไม่น้อยกว่าวันเริ่มต้น");try{const rows=(await API.bookings()).filter(booking=>booking.status!=="cancelled"&&booking.travelDate>=from&&booking.travelDate<=to),headers=["ต้นฉบับ","จองในงาน","วันที่จอง","เล่มที่","เลขที่","เล่มที่ (ตั๋วเรือ)","เลขที่ (ตั๋วเรือ)","ชื่อลูกค้า","เบอร์โทร","ผู้ใหญ่","เด็ก","ทารก","FOC","โปรแกรม","ราคาขาย","มัดจำเงินสด","มัดจำโอน","วันมา","วันกลับ","เดินทางโดย","สถานที่รับ","เดินทางกลับ","สถานที่กลับ","ที่พัก","ช่องทางติดต่อ","หมายเหตุ"],csv="\uFEFF"+[headers,...rows.map(bookingExcelRow)].map(row=>row.map(excelCell).join(",")).join("\r\n"),blob=new Blob([csv],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`Sabina-Booking-${from}-${to}.csv`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}catch(error){alert(error.message||"ดาวน์โหลด Excel ไม่สำเร็จ")}};
