masterDataConfig.island_addons={id:"island_addon_id",name:"island_addon_name",price:"default_price"};
documentProfiles.DIVE_RECEIPT={title:"ใบเสร็จดำน้ำ",price:true,diveOnly:true};
documentVisibilityFields["ใบเสร็จดำน้ำ"]="show_dive_receipt";
documentVisibilityLabels.show_dive_receipt="ใบเสร็จดำน้ำ";

const configureMasterDataForIsland=configureMasterDataPriceField;
configureMasterDataPriceField=function(){configureMasterDataForIsland();const island=mdCat==="island_addons",visible=["addons","island_addons","transportation_methods","accommodations"].includes(mdCat);document.getElementById("mdpDocumentVisibility").classList.toggle("hidden",!visible);document.getElementById("mdpIslandPurchaseVisibility").classList.toggle("hidden",!["addons","island_addons"].includes(mdCat));document.getElementById("mdpDiveReceiptVisibility").classList.toggle("hidden",!island)};
const openMasterDataEditorForIsland=openMasterDataEditor;
openMasterDataEditor=function(){openMasterDataEditorForIsland();document.getElementById("mdpShowDiveReceipt").checked=mdCat==="island_addons";if(mdCat==="island_addons"){document.getElementById("mdpShowMoneyReceipt").checked=true;document.getElementById("mdpShowEquipmentSlip").checked=false;document.getElementById("mdpShowIslandPurchaseOrder").checked=true}configureMasterDataPriceField()};
const editMasterDataItemForIsland=editMasterDataProItem;
editMasterDataProItem=function(index){editMasterDataItemForIsland(index);const row=mdRows[index]||{};document.getElementById("mdpShowDiveReceipt").checked=row.show_dive_receipt!==false;configureMasterDataPriceField()};
const masterVisibilityForIsland=masterDataDocumentVisibility;
masterDataDocumentVisibility=function(){return{...masterVisibilityForIsland(),show_dive_receipt:document.getElementById("mdpShowDiveReceipt").checked}};

function islandMasterConfiguration(item){return item.documentVisibility||(master.islandAddOns||[]).find(row=>row.island_addon_id===item.id)||{show_money_receipt:true,show_island_purchase_order:true,show_dive_receipt:true}}
const addonConfigurationBeforeIslandMaster=addonConfiguration;
addonConfiguration=function(item){const islandMaster=(master.islandAddOns||[]).some(row=>row.island_addon_id===item.id);return item.source==="island"||islandMaster?islandDocumentVisibility(item):addonConfigurationBeforeIslandMaster(item)};
islandDocumentVisibility=function(item){const config=islandMasterConfiguration(item);return{show_register:config.show_register===true,show_money_receipt:config.show_money_receipt!==false,show_equipment_slip:config.show_equipment_slip===true,show_van_receipt:config.show_van_receipt===true,show_boat_ticket:config.show_boat_ticket===true,show_island_purchase_order:config.show_island_purchase_order!==false,show_dive_receipt:config.show_dive_receipt!==false}};
addIslandAddonRow=function(){const leader=passengers[0],source=(master.islandAddOns||[])[0];if(!leader)return;if(!source)return alert("ยังไม่มี Island Add-on ใน Master Data กรุณาเพิ่มรายการก่อน");leader.islandAddOns??=[];leader.islandAddOns.push({id:source.island_addon_id,name:source.island_addon_name,qty:1,price:Number(source.default_price||0),defaultPrice:Number(source.default_price||0),paymentMethod:"",receivedBy:currentUser?.displayName||"",source:"island",documentVisibility:islandDocumentVisibility({id:source.island_addon_id})});renderPassengers();refreshSummary()};
updateIslandAddon=function(index,field,value){const item=passengers[0]?.islandAddOns?.[index];if(!item)return;if(field==="masterItemId"){const source=(master.islandAddOns||[]).find(row=>row.island_addon_id===value);if(!source)return;Object.assign(item,{id:source.island_addon_id,name:source.island_addon_name,price:Number(source.default_price||0),defaultPrice:Number(source.default_price||0),source:"island",documentVisibility:islandDocumentVisibility({id:source.island_addon_id})});renderPassengers();refreshSummary();return}if(["qty","price"].includes(field))item[field]=Math.max(Number(value||0),0);else if(field.startsWith("show_")){item.documentVisibility=islandDocumentVisibility(item);item.documentVisibility[field]=Boolean(value)}else item[field]=value;refreshSummary()};
islandAddonEditor=function(){const items=passengers[0]?.islandAddOns||[],masterRows=master.islandAddOns||[],documents=[["show_register","Register"],["show_money_receipt","ใบสำคัญรับเงิน"],["show_equipment_slip","ใบเสร็จอุปกรณ์"],["show_van_receipt","ใบรถตู้"],["show_boat_ticket","ตั๋วเรือ"],["show_island_purchase_order","ใบสั่งซื้อจากเกาะ"],["show_dive_receipt","ใบเสร็จดำน้ำ"]];return`<b>Island Add-on / รายการดำน้ำ</b><p class="muted">เลือกรายการจาก Master Data ราคาเริ่มต้นจะถูกเติมให้อัตโนมัติและแก้เฉพาะ Booking นี้ได้</p>${items.map((item,index)=>{item.source="island";const visibility=islandDocumentVisibility(item),hasCurrent=masterRows.some(row=>row.island_addon_id===item.id),options=[...(!hasCurrent&&item.id?[{island_addon_id:item.id,island_addon_name:`${item.name} (รายการเดิม)`}]:[]),...masterRows];return`<div class="island-addon-row"><div class="form-grid"><div><label>รายการ</label><select onchange="updateIslandAddon(${index},'masterItemId',this.value)">${options.map(row=>`<option value="${escapeHtml(row.island_addon_id)}" ${row.island_addon_id===item.id?"selected":""}>${escapeHtml(row.island_addon_name)}</option>`).join("")}</select></div><div><label>จำนวน</label><input type="number" min="0" value="${Number(item.qty||1)}" onchange="updateIslandAddon(${index},'qty',this.value)"></div><div><label>ราคา</label><input type="number" min="0" step="0.01" value="${Number(item.price||0)}" onchange="updateIslandAddon(${index},'price',this.value)"></div><div><label>ช่องทางชำระเงิน</label><select onchange="updateIslandAddon(${index},'paymentMethod',this.value)"><option value="">ไม่ระบุ</option>${(master.paymentMethods||[]).map(method=>`<option value="${escapeHtml(method.method_name)}" ${item.paymentMethod===method.method_name?"selected":""}>${escapeHtml(method.method_name)}</option>`).join("")}</select></div></div><div class="document-visibility-options">${documents.map(([field,label])=>`<label><input type="checkbox" ${visibility[field]?"checked":""} onchange="updateIslandAddon(${index},'${field}',this.checked)"> ${label}</label>`).join("")}</div><button type="button" class="btn danger" onclick="removeIslandAddon(${index})">ลบรายการ</button></div>`}).join("")}<button type="button" class="btn soft" onclick="addIslandAddonRow()">+ เพิ่ม Island Add-on จาก Master Data</button>`};

const groupedItemsBeforeDiveReceipt=documentGroupedItems;
documentGroupedItems=function(booking,profile){if(!profile?.diveOnly)return groupedItemsBeforeDiveReceipt(booking,profile);const groups=new Map();for(const person of booking.passengers||[])for(const item of person.islandAddOns||[]){if(!addonVisibleOnDocument({...item,source:"island"},profile))continue;const qty=Number(item.qty||1),unit=Number(item.price||0),name=item.name||"Island Add-on",key=`${item.id||name}:${unit}`,row=groups.get(key)||{name,qty:0,unit,total:0};row.qty+=qty;row.total+=qty*unit;groups.set(key,row)}return[...groups.values()]};
